<template>
  <div>
    <ArticleWrapper></ArticleWrapper>
    <ArticleWrapper></ArticleWrapper>
    <ArticleWrapper></ArticleWrapper>
    <ArticleWrapper></ArticleWrapper>
    <ArticleWrapper></ArticleWrapper>
    <ArticleWrapper></ArticleWrapper>
  </div>
</template>